<?php
/**
 * This file was generated by ChronosGenerator wcmf-1.0.18.0001 from model.uml.
 * Manual modifications should be placed inside the protected regions.
 */
namespace app\src\model\wcmf\_base;

use wcmf\lib\model\Node;
use wcmf\lib\persistence\ObjectId;

/**
 * UserConfig
 */
abstract class UserConfigBase extends Node {

  /**
   * Constructor
   * @param oid ObjectId instance (optional)
   */
  public function __construct(ObjectId $oid=null, array $initialData=null) {
    if ($oid == null) {
      $oid = new ObjectId('app.src.model.wcmf.UserConfig');
    }
    parent::__construct($oid, $initialData);
  }

  /**
   * Get the User instances in the User relation
   * @return Array of User instances
   */
  public function getUserList() {
    return $this->getValue('User');
  }

  /**
   * Set the User instances in the User relation
   * @param nodeList Array of User instances
   */
  public function setUserList(array $nodeList) {
    $this->setValue('User', null);
    foreach ($nodeList as $node) {
      $this->addNode($node, 'User');
    }
  }
}
