<?php
/**
 * This file was generated by ChronosGenerator wcmf-1.0.18.0001 from model.uml.
 * Manual modifications should be placed inside the protected regions.
 */
namespace app\src\model\wcmf\_base;

use wcmf\lib\security\principal\impl\AbstractUser;
use wcmf\lib\persistence\ObjectId;

/**
 * User
 */
abstract class UserBase extends AbstractUser {

  /**
   * Constructor
   * @param oid ObjectId instance (optional)
   */
  public function __construct(ObjectId $oid=null, array $initialData=null) {
    if ($oid == null) {
      $oid = new ObjectId('app.src.model.wcmf.User');
    }
    parent::__construct($oid, $initialData);
  }

  /**
   * Get the UserConfig instances in the UserConfig relation
   * @return Array of UserConfig instances
   */
  public function getUserConfigList() {
    return $this->getValue('UserConfig');
  }

  /**
   * Set the UserConfig instances in the UserConfig relation
   * @param nodeList Array of UserConfig instances
   */
  public function setUserConfigList(array $nodeList) {
    $this->setValue('UserConfig', null);
    foreach ($nodeList as $node) {
      $this->addNode($node, 'UserConfig');
    }
  }

  /**
   * Get the Role instances in the Role relation
   * @return Array of Role instances
   */
  public function getRoleList() {
    return $this->getValue('Role');
  }

  /**
   * Set the Role instances in the Role relation
   * @param nodeList Array of Role instances
   */
  public function setRoleList(array $nodeList) {
    $this->setValue('Role', null);
    foreach ($nodeList as $node) {
      $this->addNode($node, 'Role');
    }
  }
}
