<?php
/**
 * This file was generated by ChronosGenerator wcmf-1.0.15.0001 from model.uml.
 * Manual modifications should be placed inside the protected regions.
 */
namespace app\src\model\_base;

use app\src\model\Location;

use wcmf\lib\i18n\Message;
use wcmf\lib\model\mapper\NodeUnifiedRDBMapper;
use wcmf\lib\model\mapper\RDBAttributeDescription;
use wcmf\lib\model\mapper\RDBManyToManyRelationDescription;
use wcmf\lib\model\mapper\RDBManyToOneRelationDescription;
use wcmf\lib\model\mapper\RDBOneToManyRelationDescription;
use wcmf\lib\persistence\ReferenceDescription;
use wcmf\lib\persistence\ObjectId;

/**
 * LocationRDBMapper maps Location Nodes to the database.
 */
class LocationRDBMapper extends NodeUnifiedRDBMapper {

  /**
   * @see RDBMapper::getType()
   */
  public function getType() {
    return 'app.src.model.Location';
  }

  /**
   * @see PersistenceMapper::getTypeDisplayName()
   */
  public function getTypeDisplayName(Message $message) {
    return $message->getText("Location");
  }

  /**
   * @see PersistenceMapper::getTypeDescription()
   */
  public function getTypeDescription(Message $message) {
    return $message->getText("");
  }

  /**
   * @see PersistenceMapper::getAttributeDisplayName()
   */
  public function getAttributeDisplayName($name, Message $message) {
    $displayName = $name;
    if (false) {}
      elseif ($name == 'id') { $displayName = $message->getText("id"); }
      elseif ($name == 'name') { $displayName = $message->getText("name"); }
      elseif ($name == 'category') { $displayName = $message->getText("category"); }
      elseif ($name == 'address') { $displayName = $message->getText("address"); }
      elseif ($name == 'notes') { $displayName = $message->getText("notes"); }
      elseif ($name == 'user') { $displayName = $message->getText("user"); }
      elseif ($name == 'created') { $displayName = $message->getText("created"); }
      elseif ($name == 'creator') { $displayName = $message->getText("creator"); }
      elseif ($name == 'modified') { $displayName = $message->getText("modified"); }
      elseif ($name == 'last_editor') { $displayName = $message->getText("last_editor"); }
    return $displayName;
  }

  /**
   * @see PersistenceMapper::getAttributeDescription()
   */
  public function getAttributeDescription($name, Message $message) {
    $description = $name;
    if (false) {}
      elseif ($name == 'id') { $description = $message->getText(""); }
      elseif ($name == 'name') { $description = $message->getText(""); }
      elseif ($name == 'category') { $description = $message->getText(""); }
      elseif ($name == 'address') { $description = $message->getText(""); }
      elseif ($name == 'notes') { $description = $message->getText(""); }
      elseif ($name == 'user') { $description = $message->getText(""); }
      elseif ($name == 'created') { $description = $message->getText(""); }
      elseif ($name == 'creator') { $description = $message->getText(""); }
      elseif ($name == 'modified') { $description = $message->getText(""); }
      elseif ($name == 'last_editor') { $description = $message->getText(""); }
    return $description;
  }

  /**
   * @see PersistenceMapper::getPkNames()
   */
  public function getPkNames() {
    return ['id'];
  }

  /**
   * @see PersistenceMapper::getProperties()
   */
  public function getProperties() {
    return [
      'isSearchable' => true,
      'displayValues' => ['name', 'category', 'user'],
// PROTECTED REGION ID(app/src/model/_base/LocationRDBMapper.php/Properties) ENABLED START
// PROTECTED REGION END
    ];
  }

  /**
   * @see RDBMapper::getOwnDefaultOrder()
   */
  public function getOwnDefaultOrder($roleName=null) {
    $orderDefs = [];
    if ($roleName == null) {
      $orderDefs[] = ['sortFieldName' => 'sortkey', 'sortDirection' => 'ASC', 'isSortkey' => true];
    }
    return $orderDefs;
  }

  /**
   * @see RDBMapper::getRelationDescriptions()
   */
  protected function getRelationDescriptions() {
    return [
      'Rating' => new RDBOneToManyRelationDescription(
        'app.src.model.Location', 'Location', 'app.src.model.Rating', 'Rating',
        '1', '1', '0', 'unbounded', 'none', 'composite', 'true', 'true', 'child', 'id', 'fk_location_id'
      ),
      'Image' => new RDBOneToManyRelationDescription(
        'app.src.model.Location', 'Location', 'app.src.model.Image', 'Image',
        '1', '1', '0', 'unbounded', 'none', 'composite', 'true', 'true', 'child', 'id', 'fk_location_id'
      ),
    ];
  }

  /**
   * @see RDBMapper::getAttributeDescriptions()
   */
  protected function getAttributeDescriptions() {
    return [
     /**
      *
      */
      'id' => new RDBAttributeDescription('id', '', ['DATATYPE_IGNORE'], null, '', '', false, 'text', 'text', 'Location', 'id'),
     /**
      *
      */
      'name' => new RDBAttributeDescription('name', 'String', ['DATATYPE_ATTRIBUTE'], null, '', '', true, 'text', 'text', 'Location', 'name'),
     /**
      *
      */
      'category' => new RDBAttributeDescription('category', 'String', ['DATATYPE_ATTRIBUTE'], null, '', '', true, 'select:{"list":{"type":"node","types":["Category"]}}', 'text', 'Location', 'category'),
     /**
      *
      */
      'address' => new RDBAttributeDescription('address', 'String', ['DATATYPE_ATTRIBUTE'], null, '', '', true, 'textarea', 'text', 'Location', 'address'),
     /**
      *
      */
      'notes' => new RDBAttributeDescription('notes', 'String', ['DATATYPE_ATTRIBUTE'], null, '', '', true, 'ckeditor:{"toolbarSet":"wcmf"}', 'text', 'Location', 'notes'),
     /**
      *
      */
      'user' => new RDBAttributeDescription('user', 'String', ['DATATYPE_ATTRIBUTE'], null, '', '', true, 'select:{"list":{"type":"node","types":["User"]}}', 'text', 'Location', 'user'),
     /**
      *
      */
      'created' => new RDBAttributeDescription('created', 'Date', ['DATATYPE_ATTRIBUTE', 'GROUP_INTERNAL'], null, '', '', false, 'text', 'text', 'Location', 'created'),
     /**
      *
      */
      'creator' => new RDBAttributeDescription('creator', 'String', ['DATATYPE_ATTRIBUTE', 'GROUP_INTERNAL'], null, '', '', false, 'text', 'text', 'Location', 'creator'),
     /**
      *
      */
      'modified' => new RDBAttributeDescription('modified', 'Date', ['DATATYPE_ATTRIBUTE', 'GROUP_INTERNAL'], null, '', '', false, 'text', 'text', 'Location', 'modified'),
     /**
      *
      */
      'last_editor' => new RDBAttributeDescription('last_editor', 'String', ['DATATYPE_ATTRIBUTE', 'GROUP_INTERNAL'], null, '', '', false, 'text', 'text', 'Location', 'last_editor'),
      /**
       * Sort key for ordering
       */
      'sortkey' => new RDBAttributeDescription('sortkey', 'Float', ['DATATYPE_IGNORE'], null, 'regexp:{"pattern":"/^[0-9.]*$/"}', '', true, 'text[class="tiny"]', 'text', 'Location', 'sortkey'),
    ];
  }

  /**
   * @see RDBMapper::createObject()
   */
  protected function createObject(ObjectId $oid=null, array $initialData=null) {
    return new Location($oid, $initialData);
  }

  /**
   * @see NodeUnifiedRDBMapper::getTableName()
   */
  protected function getTableName() {
    return 'Location';
  }
}

/**
 * Additional names to be included by l10n tools ([Pl.]: plural forms)
 * - $message->getText("Location [Pl.]")
 * - $message->getText("Rating")
 * - $message->getText("Rating [Pl.]")
 * - $message->getText("Image")
 * - $message->getText("Image [Pl.]")
 * Restrictions descriptions to be included by l10n tools
 */
