<?php
/**
 * This file was generated by ChronosGenerator wcmf-1.0.15.0001 from model.uml.
 * Manual modifications should be placed inside the protected regions.
 */
namespace app\src\model\_base;

use app\src\model\EntityBase;
use wcmf\lib\persistence\ObjectId;

/**
 * Location
 */
abstract class LocationBase extends EntityBase {

  /**
   * Constructor
   * @param oid ObjectId instance (optional)
   */
  public function __construct(ObjectId $oid=null, array $initialData=null) {
    if ($oid == null) {
      $oid = new ObjectId('app.src.model.Location');
    }
    parent::__construct($oid, $initialData);
  }

  /**
   * Get the Rating instances in the Rating relation
   * @return Array of Rating instances
   */
  public function getRatingList() {
    return $this->getValue('Rating');
  }

  /**
   * Set the Rating instances in the Rating relation
   * @param nodeList Array of Rating instances
   */
  public function setRatingList(array $nodeList) {
    $this->setValue('Rating', null);
    foreach ($nodeList as $node) {
      $this->addNode($node, 'Rating');
    }
  }

  /**
   * Get the Image instances in the Image relation
   * @return Array of Image instances
   */
  public function getImageList() {
    return $this->getValue('Image');
  }

  /**
   * Set the Image instances in the Image relation
   * @param nodeList Array of Image instances
   */
  public function setImageList(array $nodeList) {
    $this->setValue('Image', null);
    foreach ($nodeList as $node) {
      $this->addNode($node, 'Image');
    }
  }
}
