<?php
/**
 * This file was generated by ChronosGenerator wcmf-1.0.16.0001 from model.uml.
 * Manual modifications should be placed inside the protected regions.
 */
namespace app\src\controller\_base;

use wcmf\lib\presentation\Controller;
use wcmf\lib\validation\ValidationException;

/**
 * RootController
 */
abstract class RootControllerBase extends Controller {

  /**
   * @see Controller::doExecute()
   */
  protected function doExecute($method=null) {
    $method = $method != null ? $method : 'executeFallback';
    if (method_exists($this, $method)) {
      // handle request/response parameters
      $request = $this->getRequest();
      $response = $this->getResponse();
      $params = [];

      call_user_func_array([$this, $method], $params);
    }
    else {
      throw new \Exception("The method '".$method."' is not defined in class ".get_class($this));
    }
  }

  /**
   * Handle a validation exception.
   * NOTE: Subclasses override this method for custom exception handling.
   * @param $ex ValidationException
   */
  protected function validationFailed(ValidationException $ex) {}

  /**
   * Fallback method to execute, if no concrete method is defined for the request
   * NOTE: Subclasses implement this method, if they must handle requests
   * that do not map to a concrete method.
   */
  protected function executeFallback() {
    throw new \Exception(get_class($this).' must implement method executeFallback.');
  }
}
