<?php
/**
 * This file was generated by ChronosGenerator wcmf-1.0.15.0001 from model.uml.
 * Manual modifications should be placed inside the protected regions.
 */
namespace app\src\model;

use app\src\model\_base\CategoryBase;
// PROTECTED REGION ID(app/src/model/Category.php/Import) ENABLED START
// PROTECTED REGION END

/**
 * Category
 *
 * @var id
 * @var name (String)
 * @var color (String)
 * @var created (Date)
 * @var creator (String)
 * @var modified (Date)
 * @var last_editor (String)
 */
class Category extends CategoryBase {
// PROTECTED REGION ID(app/src/model/Category.php/Body) ENABLED START
// PROTECTED REGION END
}
