<?php
/**
 * This file was generated by ChronosGenerator wcmf-1.0.18.0001 from model.uml.
 * Manual modifications should be placed inside the protected regions.
 */
namespace app\src\model;

use app\src\model\_base\ImageBase;
// PROTECTED REGION ID(app/src/model/Image.php/Import) ENABLED START
// PROTECTED REGION END

/**
 * Image
 *
 * @var id
 * @var fk_location_id
 * @var filename (String)
 * @var created (Date)
 * @var creator (String)
 * @var modified (Date)
 * @var last_editor (String)
 * @rel Location (app.src.model.Location, n:1)
 */
class Image extends ImageBase {
// PROTECTED REGION ID(app/src/model/Image.php/Body) ENABLED START
// PROTECTED REGION END
}
