<?php
/**
 * This file was generated by ChronosGenerator wcmf-1.0.15.0001 from model.uml.
 * Manual modifications should be placed inside the protected regions.
 */
namespace app\src\model;

use app\src\model\_base\LocationBase;
// PROTECTED REGION ID(app/src/model/Location.php/Import) ENABLED START
// PROTECTED REGION END

/**
 * Location
 *
 * @var id
 * @var category
 * @var name (String)
 * @var user (String)
 * @var address (String)
 * @var website (String)
 * @var notes (String)
 * @var archived (Integer)
 * @var created (Date)
 * @var creator (String)
 * @var modified (Date)
 * @var last_editor (String)
 * @rel Rating (app.src.model.Rating, 1:n)
 * @rel Image (app.src.model.Image, 1:n)
 * @rel Category (app.src.model.Category, n:1)
 */
class Location extends LocationBase {
// PROTECTED REGION ID(app/src/model/Location.php/Body) ENABLED START
// PROTECTED REGION END
}
