<?php
/**
 * This file was generated by ChronosGenerator wcmf-1.0.15.0001 from model.uml.
 * Manual modifications should be placed inside the protected regions.
 */
namespace app\src\model;

use app\src\model\_base\RatingBase;
// PROTECTED REGION ID(app/src/model/Rating.php/Import) ENABLED START
// PROTECTED REGION END

/**
 * Rating
 *
 * @var id
 * @var fk_location_id
 * @var value (String)
 * @var  (Location)
 * @var created (Date)
 * @var creator (String)
 * @var modified (Date)
 * @var last_editor (String)
 * @rel Location (app.src.model.Location, n:1)
 */
class Rating extends RatingBase {
// PROTECTED REGION ID(app/src/model/Rating.php/Body) ENABLED START
// PROTECTED REGION END
  /**
   * Rating::getnull()
   * @return Location
   */
  public function getnull() {
// PROTECTED REGION ID(app/src/model/Rating.php/Methods/getnull) ENABLED START
// PROTECTED REGION END
  }
}
