<?php
/**
 * This file was generated by ChronosGenerator wcmf-1.0.16.0001 from model.uml.
 * Manual modifications should be placed inside the protected regions.
 */
namespace app\src\model\wcmf;

use app\src\model\wcmf\_base\DBSequenceBase;
// PROTECTED REGION ID(app/src/model/wcmf/DBSequence.php/Import) ENABLED START
// PROTECTED REGION END

/**
 * DBSequence
 *
 * @var table (String)
 * @var id (Integer)
 */
class DBSequence extends DBSequenceBase {
// PROTECTED REGION ID(app/src/model/wcmf/DBSequence.php/Body) ENABLED START
// PROTECTED REGION END
}
