<?php
/**
 * This file was generated by ChronosGenerator wcmf-1.0.15.0001 from model.uml.
 * Manual modifications should be placed inside the protected regions.
 */
namespace app\src\model\wcmf;

use app\src\model\wcmf\_base\LanguageBase;
// PROTECTED REGION ID(app/src/model/wcmf/Language.php/Import) ENABLED START
// PROTECTED REGION END

/**
 * A language for which a translation of the model can be created. The code is arbitrary but it is recommended to use the ISO language codes (en, de, it, ...).
 *
 * @var id
 * @var name (String)
 * @var code (String)
 */
class Language extends LanguageBase {
// PROTECTED REGION ID(app/src/model/wcmf/Language.php/Body) ENABLED START
// PROTECTED REGION END
}
