<?php
/**
 * This file was generated by ChronosGenerator wcmf-1.0.16.0001 from model.uml.
 * Manual modifications should be placed inside the protected regions.
 */
namespace app\src\model\wcmf;

use app\src\model\wcmf\_base\LockBase;
// PROTECTED REGION ID(app/src/model/wcmf/Lock.php/Import) ENABLED START
// PROTECTED REGION END

/**
 * Lock
 *
 * @var id
 * @var objectid (String)
 * @var login (String)
 * @var created (Date)
 */
class Lock extends LockBase {
// PROTECTED REGION ID(app/src/model/wcmf/Lock.php/Body) ENABLED START
// PROTECTED REGION END
}
