<?php
/**
 * This file was generated by ChronosGenerator wcmf-1.0.16.0001 from model.uml.
 * Manual modifications should be placed inside the protected regions.
 */
namespace app\src\model\wcmf;

use app\src\model\wcmf\_base\NMUserRoleBase;
// PROTECTED REGION ID(app/src/model/wcmf/NMUserRole.php/Import) ENABLED START
// PROTECTED REGION END

/**
 * NMUserRole
 *
 * @var fk_role_id
 * @var fk_user_id
 * @rel User (app.src.model.wcmf.User, n:1)
 * @rel Role (app.src.model.wcmf.Role, n:1)
 */
class NMUserRole extends NMUserRoleBase {
// PROTECTED REGION ID(app/src/model/wcmf/NMUserRole.php/Body) ENABLED START
// PROTECTED REGION END
}
