<?php
/**
 * This file was generated by ChronosGenerator wcmf-1.0.18.0001 from model.uml.
 * Manual modifications should be placed inside the protected regions.
 */
namespace app\src\model\wcmf;

use app\src\model\wcmf\_base\PermissionBase;
// PROTECTED REGION ID(app/src/model/wcmf/Permission.php/Import) ENABLED START
// PROTECTED REGION END

/**
 * Permission
 *
 * @var id
 * @var resource (String)
 * @var context (String)
 * @var action (String)
 * @var roles (String)
 */
class Permission extends PermissionBase {
// PROTECTED REGION ID(app/src/model/wcmf/Permission.php/Body) ENABLED START
// PROTECTED REGION END
}
