<?php
/**
 * This file was generated by ChronosGenerator wcmf-1.0.16.0001 from model.uml.
 * Manual modifications should be placed inside the protected regions.
 */
namespace app\src\model\wcmf;

use app\src\model\wcmf\_base\RoleBase;
// PROTECTED REGION ID(app/src/model/wcmf/Role.php/Import) ENABLED START
// PROTECTED REGION END

/**
 * Role
 *
 * @var id
 * @var name (String)
 * @rel User (app.src.model.wcmf.User, n:m)
 */
class Role extends RoleBase {
// PROTECTED REGION ID(app/src/model/wcmf/Role.php/Body) ENABLED START
// PROTECTED REGION END
}
