<?php
/**
 * This file was generated by ChronosGenerator wcmf-1.0.18.0001 from model.uml.
 * Manual modifications should be placed inside the protected regions.
 */
namespace app\src\model\wcmf;

use app\src\model\wcmf\_base\UserConfigBase;
// PROTECTED REGION ID(app/src/model/wcmf/UserConfig.php/Import) ENABLED START
// PROTECTED REGION END

/**
 * UserConfig
 *
 * @var id
 * @var fk_user_id
 * @var name (String)
 * @var value (String)
 * @rel User (app.src.model.wcmf.User, n:1)
 */
class UserConfig extends UserConfigBase {
// PROTECTED REGION ID(app/src/model/wcmf/UserConfig.php/Body) ENABLED START
// PROTECTED REGION END
}
